parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $injectIframeResizer: '%optime_sso_client.inject_iframe_resizer%'
#      $expirationSeconds: '%optime_sso_server.jwt.expiration%'

  Optime\Sso\Bundle\Client\:
    resource: '../'
    exclude:
      - '../DependencyInjection/'
      - '../Entity/'
      - '../OptimeSsoClientBundle.php'

#  Optime\Sso\Bundle\Client\Controller\:
#    resource: '../Controller/'
#    tags: [ 'controller.service_arguments' ]