parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $privateKey: '%optime_sso_server.jwt.secret%'
      $expirationSeconds: '%optime_sso_server.jwt.expiration%'

  Optime\Sso\Bundle\Server\:
    resource: '../'
    exclude:
      - '../DependencyInjection/'
      - '../Entity/'
      - '../OptimeSsoServerBundle.php'

  Optime\Sso\Bundle\Server\Controller\:
    resource: '../Controller/'
    tags: [ 'controller.service_arguments' ]