parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Optime\Acl\Bundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/OptimeSsoServerBundle.php'

  Optime\Sso\Bundle\Server\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]